export const HOME_PAGE = '/home';
export const HOME_PAGE_NAME = "homepage";
export const SEARCH_PAGE = '/search';
export const SEARCH_PAGE_NAME = "search page";
export const LOG_IN_WITHOUT_DEFAULT = '/login';
export const LOG_IN_PAGE = '/login/:defaultUsername?';
export const LOG_IN_PAGE_NAME = "log in page";
export const SIGN_UP_PAGE = '/signup';
export const SIGN_UP_PAGE_NAME = "sign up page";